services:
  app:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - muzz-network
  api:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/node_modules:/api/node_modules
      - ./backend:/api
    ports:
      - '3001:3001'
    networks:
      - muzz-network
networks:
  muzz-network:
    name: muzz-network

    